-- Create categories table
create table public.categories (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null unique,
  slug text not null unique,
  description text
);

-- Enable RLS
alter table public.categories enable row level security;

-- Policies
create policy "Everyone can read categories" 
  on public.categories for select 
  using (true);

create policy "Admins can manage categories" 
  on public.categories for all 
  using (auth.uid() in (select id from public.profiles where role = 'admin'));

-- Insert default categories
insert into public.categories (name, slug) values
('Handicrafts', 'handicrafts'),
('Art', 'art'),
('Textiles', 'textiles'),
('Spices', 'spices'),
('Jewelry', 'jewelry'),
('Decor', 'decor');
