-- Create FAQs table
create table public.faqs (
  id bigint generated by default as identity primary key,
  question text not null,
  answer text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.faqs enable row level security;

-- Create policies
create policy "Enable read access for all users" on public.faqs
  for select using (true);

create policy "Enable insert for admins only" on public.faqs
  for insert with check (
    auth.uid() in (
      select id from public.profiles where role = 'admin'
    )
  );

create policy "Enable update for admins only" on public.faqs
  for update using (
    auth.uid() in (
      select id from public.profiles where role = 'admin'
    )
  );

create policy "Enable delete for admins only" on public.faqs
  for delete using (
    auth.uid() in (
      select id from public.profiles where role = 'admin'
    )
  );

-- Insert some default FAQs
insert into public.faqs (question, answer) values
('How long does shipping take?', 'International shipping typically takes 7-14 business days. Express shipping is available for an additional fee.'),
('Are products authentic?', 'Yes, every product is handcrafted by verified Nepali artisans. Each item comes with a certificate of authenticity.'),
('What is your return policy?', 'We offer a 30-day return policy for unused items in original packaging. Contact us to initiate a return.');
