-- Create a table for products
create table public.products (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  category text not null,
  price decimal(10,2) not null,
  original_price decimal(10,2),
  image_url text not null,
  badge text,
  description text,
  stock_quantity integer default 0
);

-- Enable RLS
alter table public.products enable row level security;

-- Create a storage bucket for product images (if not exists)
insert into storage.buckets (id, name, public) 
values ('product-images', 'product-images', true)
on conflict (id) do nothing;

-- Policies for storage
create policy "Public Access" 
  on storage.objects for select 
  using ( bucket_id = 'product-images' );

create policy "Authenticated users can upload" 
  on storage.objects for insert 
  with check ( bucket_id = 'product-images' and auth.role() = 'authenticated' );

-- Policies for products table
-- Everyone can read products
create policy "Enable read access for all users" 
  on public.products for select 
  using (true);

-- Only admins should be able to insert/update/delete
-- For simplicity in this demo, we will allow any authenticated user to edit products
-- IN PRODUCTION: You would use a stricter policy like: auth.email() = 'admin@hatiya.com'
create policy "Enable write access for authenticated users" 
  on public.products for all 
  using (auth.role() = 'authenticated');
